apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hypershift-operator-release-413
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-23/hypershift-operator-release-413@sha256:8fba1ec38c315c106b759c359ef85fc0af8be83165ae3d9b0afb7ecde5de3531
        name: container-image
        resources: {}
status: {}
