apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hypershift-operator-release-413
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-23/hypershift-operator-release-413@sha256:7b55f6e6d08b779890de2ccdbdf4919a16a885012fe7f912cff8ca652679d703
        name: container-image
        resources: {}
status: {}
