apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hypershift-operator-release-413
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-23/hypershift-operator-release-413@sha256:b8a9f8d4498a2e18c34052d9803e9b273f0e7db0b9a9d6cb387bb1fef2796714
        name: container-image
        resources: {}
status: {}
