apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-operator-release-413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-operator-release-413
    app.kubernetes.io/part-of: mce-23
  name: hypershift-operator-release-413
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hypershift-operator-release-413
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hypershift-operator-release-413
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-23/hypershift-operator-release-413@sha256:2e68a8daca65d7e4f083a0f3a0e20a9d841e9ab045fb94f47351126a520edc69
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
