apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-operator-release-413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-operator-release-413
    app.kubernetes.io/part-of: mce-23
  name: hypershift-operator-release-413
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: hypershift-operator-release-413
status:
  loadBalancer: {}
